stages:
  - test
  - check

include:
# Issue check
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/check-issue@~latest

# Build and test
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      anod-args: run build_test_$ACI_TRACK
      cpus: 8
      needs: []
